/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BiChevronLeft: typeof import('./src/components/icons/BiChevronLeft.vue')['default']
    BiChevronRight: typeof import('./src/components/icons/BiChevronRight.vue')['default']
    BiGear: typeof import('./src/components/icons/BiGear.vue')['default']
    BiMoonStarsFill: typeof import('./src/components/icons/BiMoonStarsFill.vue')['default']
    BiSun: typeof import('./src/components/icons/BiSun.vue')['default']
    CodeContainer: typeof import('./src/components/code-container/CodeContainer.vue')['default']
    CodeTable: typeof import('./src/components/code-container/CodeTable.vue')['default']
    CodeTableTr: typeof import('./src/components/code-container/CodeTableTr.vue')['default']
    DiffActiveLineContainer: typeof import('./src/components/code-container/DiffActiveLineContainer.vue')['default']
    DiffDisplayAlignedSwitch: typeof import('./src/components/DiffDisplayAlignedSwitch.vue')['default']
    DiffLegendItems: typeof import('./src/components/DiffLegendItems.vue')['default']
    DiffLinesContainer: typeof import('./src/components/code-container/DiffLinesContainer.vue')['default']
    DiffScriptsSidebar: typeof import('./src/components/DiffScriptsSidebar.vue')['default']
    DiffSetting: typeof import('./src/components/DiffSetting.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    FileSelectItem: typeof import('./src/components/FileSelectItem.vue')['default']
    GithubFilesSelector: typeof import('./src/components/GithubFilesSelector.vue')['default']
    LanguageSelector: typeof import('./src/components/LanguageSelector.vue')['default']
    LyChevronDown: typeof import('./src/components/icons/LyChevronDown.vue')['default']
    LyChevronUp: typeof import('./src/components/icons/LyChevronUp.vue')['default']
    LyFileNormal: typeof import('./src/components/icons/LyFileNormal.vue')['default']
    PageMenuContainer: typeof import('./src/components/page-menu/PageMenuContainer.vue')['default']
    RootReadme: typeof import('./src/components/RootReadme.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggleButton: typeof import('./src/components/ThemeToggleButton.vue')['default']
    ToBottomButton: typeof import('./src/components/page-menu/ToBottomButton.vue')['default']
    ToTopButton: typeof import('./src/components/page-menu/ToTopButton.vue')['default']
  }
}
